// Validation tests: compare zxdrfile output against mdtraj reference data.
//
// Reference JSON generated by scripts/generate_reference.py using mdtraj.
// Format: { "natoms": N, "n_frames": N, "frames": [{ "step": N, "time": F, "box": [[3x3]], "coords": [F...] }, ...] }
//
const std = @import("std");
const xdrfile = @import("xdrfile.zig");
const XtcReader = xdrfile.XtcReader;
const XtcError = xdrfile.XtcError;
const TrrReader = xdrfile.TrrReader;
const TrrError = xdrfile.TrrError;

const ReferenceFrame = struct {
    step: i64,
    time: f64,
    lambda: f64 = 0,
    box: ?[3][3]f64 = null,
    coords: []f64,
};

const Reference = struct {
    natoms: i64,
    n_frames: i64,
    frames: []ReferenceFrame,
};

fn parseReference(allocator: std.mem.Allocator, path: []const u8) !std.json.Parsed(Reference) {
    const file = try std.fs.cwd().openFile(path, .{});
    defer file.close();

    const data = try file.readToEndAlloc(allocator, 64 * 1024 * 1024);
    defer allocator.free(data);

    return std.json.parseFromSlice(Reference, allocator, data, .{ .allocate = .alloc_always });
}

// Tolerance for coordinate comparison (nm).
// XTC uses lossy compression, so we allow larger tolerance.
const XTC_TOLERANCE: f32 = 0.001;
const TRR_TOLERANCE: f32 = 0.0001;

test "validate XTC against mdtraj reference" {
    const allocator = std.testing.allocator;

    const parsed = parseReference(allocator, "test_data/1l2y_xtc_reference.json") catch |err| {
        std.debug.print("Skipping XTC validation: reference not found ({any})\n", .{err});
        return;
    };
    defer parsed.deinit();
    const ref = parsed.value;

    var reader = try XtcReader.open(allocator, "test_data/1l2y.xtc");
    defer reader.close();

    try std.testing.expectEqual(@as(i32, @intCast(ref.natoms)), reader.getNumAtoms());

    var frame_idx: usize = 0;
    while (frame_idx < ref.frames.len) : (frame_idx += 1) {
        var frame = reader.readFrame() catch |err| {
            if (err == XtcError.EndOfFile) break;
            return err;
        };
        defer frame.deinit(allocator);

        const ref_frame = ref.frames[frame_idx];

        // Validate box
        if (ref_frame.box) |ref_box| {
            for (0..3) |i| {
                for (0..3) |j| {
                    try std.testing.expectApproxEqAbs(
                        @as(f32, @floatCast(ref_box[i][j])),
                        frame.box[i][j],
                        XTC_TOLERANCE,
                    );
                }
            }
        }

        // Validate coordinates
        try std.testing.expectEqual(ref_frame.coords.len, frame.coords.len);
        for (0..frame.coords.len) |i| {
            const expected: f32 = @floatCast(ref_frame.coords[i]);
            try std.testing.expectApproxEqAbs(expected, frame.coords[i], XTC_TOLERANCE);
        }
    }

    try std.testing.expectEqual(@as(usize, @intCast(ref.n_frames)), frame_idx);
}

test "validate TRR against mdtraj reference" {
    const allocator = std.testing.allocator;

    const parsed = parseReference(allocator, "test_data/frame0_trr_reference.json") catch |err| {
        std.debug.print("Skipping TRR validation: reference not found ({any})\n", .{err});
        return;
    };
    defer parsed.deinit();
    const ref = parsed.value;

    var reader = try TrrReader.open(allocator, "test_data/frame0.trr");
    defer reader.close();

    try std.testing.expectEqual(@as(i32, @intCast(ref.natoms)), reader.getNumAtoms());

    var frame_idx: usize = 0;
    while (frame_idx < ref.frames.len) : (frame_idx += 1) {
        var frame = reader.readFrame() catch |err| {
            if (err == TrrError.EndOfFile) break;
            return err;
        };
        defer frame.deinit(allocator);

        const ref_frame = ref.frames[frame_idx];

        // Validate time
        try std.testing.expectApproxEqAbs(
            @as(f32, @floatCast(ref_frame.time)),
            frame.time,
            TRR_TOLERANCE,
        );

        // Validate box
        if (ref_frame.box) |ref_box| {
            for (0..3) |i| {
                for (0..3) |j| {
                    try std.testing.expectApproxEqAbs(
                        @as(f32, @floatCast(ref_box[i][j])),
                        frame.box[i][j],
                        TRR_TOLERANCE,
                    );
                }
            }
        }

        // Validate coordinates
        if (frame.coords) |coords| {
            try std.testing.expectEqual(ref_frame.coords.len, coords.len);
            for (0..coords.len) |i| {
                const expected: f32 = @floatCast(ref_frame.coords[i]);
                try std.testing.expectApproxEqAbs(expected, coords[i], TRR_TOLERANCE);
            }
        }
    }

    try std.testing.expectEqual(@as(usize, @intCast(ref.n_frames)), frame_idx);
}
